import React, { useState, useEffect } from 'react';
import { ShieldAlert, Search, RefreshCw, Eye, Calendar, UserCheck } from 'lucide-react';
import { fetchAuditLogs } from '../services/api';
import './AuditLogs.css';

export default function AuditLogs({ token }) {
  const [logs, setLogs] = useState([]);
  const [filteredLogs, setFilteredLogs] = useState([]);
  const [search, setSearch] = useState('');
  const [riskFilter, setRiskFilter] = useState('All');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [selectedLog, setSelectedLog] = useState(null);

  const loadLogs = async () => {
    setIsLoading(true);
    setError('');
    try {
      const data = await fetchAuditLogs(token);
      if (data && data.logs) {
        setLogs(data.logs);
        setFilteredLogs(data.logs);
      }
    } catch (err) {
      setError(err.message || 'Failed to fetch audit logs.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadLogs();
  }, [token]);

  useEffect(() => {
    let result = logs;

    if (search.trim() !== '') {
      const q = search.toLowerCase();
      result = result.filter(
        (log) =>
          log.query.toLowerCase().includes(q) ||
          log.decision_summary.toLowerCase().includes(q) ||
          log.intent.toLowerCase().includes(q) ||
          log.user_role.toLowerCase().includes(q)
      );
    }

    if (riskFilter !== 'All') {
      result = result.filter((log) => log.risk_level === riskFilter);
    }

    setFilteredLogs(result);
  }, [search, riskFilter, logs]);

  const getRiskBadgeClass = (level) => {
    const l = level.toLowerCase();
    if (l === 'high') return 'badge-danger';
    if (l === 'medium') return 'badge-warning';
    return 'badge-success';
  };

  return (
    <div className="audit-logs-wrapper animate-fade-in">
      <div className="audit-header-panel">
        <div>
          <h1 className="audit-title">System Compliance Audit Logs</h1>
          <p className="audit-subtitle">Conversational risk auditing records generated by the multi-agent pipeline</p>
        </div>
        <button className="refresh-btn glass" onClick={loadLogs} disabled={isLoading}>
          <RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} /> Refresh Logs
        </button>
      </div>

      {error && <div className="audit-alert error"><ShieldAlert size={18} /> <span>{error}</span></div>}

      <div className="audit-filters-bar glass">
        <div className="search-box">
          <Search size={18} className="search-icon" />
          <input
            type="text"
            placeholder="Search query, decision summary, intent, role..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="filter-dropdown">
          <label>Risk Level:</label>
          <select value={riskFilter} onChange={(e) => setRiskFilter(e.target.value)}>
            <option value="All">All Risks</option>
            <option value="Low">Low Risk</option>
            <option value="Medium">Medium Risk</option>
            <option value="High">High Risk</option>
          </select>
        </div>
      </div>

      <div className="audit-table-container glass">
        {isLoading ? (
          <div className="audit-loading-state">
            <RefreshCw size={36} className="animate-spin text-accent" />
            <p>Retrieving compliance records from audit-service...</p>
          </div>
        ) : filteredLogs.length === 0 ? (
          <div className="audit-empty-state">
            <UserCheck size={48} className="text-secondary" />
            <p>No compliance audit logs found matching the filter criteria.</p>
          </div>
        ) : (
          <table className="audit-table">
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>Role</th>
                <th>Query</th>
                <th>Classified Intent</th>
                <th>Risk Level</th>
                <th>Conf.</th>
                <th>Review</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredLogs.map((log) => (
                <tr key={log.id}>
                  <td className="timestamp-cell">
                    <Calendar size={14} className="cell-icon" />
                    <span>{log.timestamp ? new Date(log.timestamp).toLocaleString() : 'N/A'}</span>
                  </td>
                  <td>
                    <span className={`role-tag ${log.user_role.toLowerCase()}`}>
                      {log.user_role}
                    </span>
                  </td>
                  <td className="truncate-cell" title={log.query}>{log.query}</td>
                  <td><span className="intent-tag">{log.intent}</span></td>
                  <td>
                    <span className={`risk-badge ${getRiskBadgeClass(log.risk_level)}`}>
                      {log.risk_level}
                    </span>
                  </td>
                  <td className="score-cell">{log.confidence_score}</td>
                  <td>
                    {log.needs_review ? (
                      <span className="review-tag active">⚠️ Flagged</span>
                    ) : (
                      <span className="review-tag clear">Clear</span>
                    )}
                  </td>
                  <td>
                    <button className="view-details-btn" onClick={() => setSelectedLog(log)}>
                      <Eye size={16} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {selectedLog && (
        <div className="audit-modal-overlay animate-fade-in" onClick={() => setSelectedLog(null)}>
          <div className="audit-modal glass" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Compliance Decision Audit Record #{selectedLog.id}</h2>
              <button className="modal-close-btn" onClick={() => setSelectedLog(null)}>✕</button>
            </div>
            <div className="modal-body">
              <div className="modal-info-grid">
                <div className="info-item">
                  <label>Timestamp</label>
                  <div>{selectedLog.timestamp ? new Date(selectedLog.timestamp).toLocaleString() : 'N/A'}</div>
                </div>
                <div className="info-item">
                  <label>User Role</label>
                  <div>{selectedLog.user_role}</div>
                </div>
                <div className="info-item">
                  <label>Classified Intent</label>
                  <div>{selectedLog.intent}</div>
                </div>
                <div className="info-item">
                  <label>Risk Assessment</label>
                  <div>
                    <span className={`risk-badge ${getRiskBadgeClass(selectedLog.risk_level)}`}>
                      {selectedLog.risk_level} Risk
                    </span>
                  </div>
                </div>
                <div className="info-item">
                  <label>Linguistics Confidence</label>
                  <div>{selectedLog.confidence_score}</div>
                </div>
                <div className="info-item">
                  <label>Needs Admin Review</label>
                  <div>
                    {selectedLog.needs_review ? (
                      <span className="review-tag active">⚠️ Yes (Flagged for violation risk)</span>
                    ) : (
                      <span className="review-tag clear">No (Safe query)</span>
                    )}
                  </div>
                </div>
              </div>

              <div className="modal-text-block">
                <label>User compliance Query</label>
                <div className="text-box">{selectedLog.query}</div>
              </div>

              <div className="modal-text-block">
                <label>Compliance Decision & Answer Summary</label>
                <div className="text-box decision-summary">{selectedLog.decision_summary}</div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
